modLoader = "javafml"
loaderVersion = "[47,)"
license = "GPL-3.0"
issueTrackerURL = "https://github.com/mmyddd/GTPonder/issues"

[[mods]]
modId = "gtponder"
version = "1.0.0"
displayName = "GT Ponder"
authors = "mmyddd"
description = '''
A client-side library that draws a real GregTech machine UI inside Create Ponder scenes.
'''

[[dependencies.gtponder]]
    modId = "forge"
    type = "required"
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.gtponder]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.gtponder]]
    modId = "gtceu"
    type = "required"
    versionRange = "*"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.gtponder]]
    modId = "create"
    type = "required"
    versionRange = "*"
    ordering = "AFTER"
    side = "BOTH"
